#!/bin/sh

start() {
    echo "Starting FBrowser"
    /FB/autorun.sh &
}

stop() {
    echo "Stopping FBrowser"
    killall autorun.sh
    killall FBrowser
}

restart() {
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

